### ISSUE TITLE
Failed to find match for filed 'rgb'

### ISSUE THREAD

**Issue by mac137** [marip8/colorized_mesh_display#13]
Hello! I am loading up and displaying .obj or .ply objects using your package but I cannot see the colour on the mesh in Rviz. I'm using Ubuntu 20.04 and ROS Noetic.

Rviz keeps saying:
```Failed to find match for field 'rgb'.
Failed to find match for field 'normal_x'.
Failed to find match for field 'normal_y'.
Failed to find match for field 'normal_z'.
Failed to find match for field 'curvature'.
```

Any idea how to fix that?

**Comment by marip8** [comment]
> Rviz keeps saying:

Those messages come from the PCL function that loads a mesh resource into a PCL mesh representation. Apparently the meshes you loaded do not contain vertex normals (`normal_x/y/z`) or point curvature information. 

> Any idea how to fix that?

This can be fixed by adding mesh normals and curvature to your mesh resource using PCL (directly or with its CLI tools) or using a mesh editing tool like Blender or Meshlab. I don't think the lack of curvature information is problematic, but the lack of vertex normals might make the mesh un-renderable (i.e. invisible). 

> I cannot see the colour on the mesh in Rviz

Can you provide some more information and screenshots about this issue? Your snippet from the PCL output does not indicate that `rgb` information is not available
- Is the mesh visible when using the `ColorizedMeshDisplay` Rviz display?
- What is the expected colorization of the mesh you are trying to display and what are you actually seeing?
- Is the scale of the mesh correct?
  - If the scale of the mesh is not in meters, the mesh can be difficult to find in Rviz because it may be orders of magnitude bigger or smaller than expected
- Have you tried using the [test executable in this repo](https://github.com/marip8/colorized_mesh_display/blob/a639e09c2c3aa1e9fa12b6d88218bade0d6b226a/src/colorized_mesh_display_test.cpp) to display your mesh?

If you can upload the mesh in question to this issue, I can take a look at it as well

**Comment by mac137** [comment]
Hej! Many thanks for your answer.

I did my tests based on your [test executable](https://github.com/marip8/colorized_mesh_display/blob/a639e09c2c3aa1e9fa12b6d88218bade0d6b226a/src/colorized_mesh_display_test.cpp). I just changed it a little so that it keeps publishing the object every 1 second:



I download the obj object from [here](https://free3d.com/3d-model/concert-stage-33747.html) and the expected outcome is this:
![image](https://user-images.githubusercontent.com/60878347/130625247-fd656b72-9178-4b1d-b439-9af410139db2.png)

whereas what I can see in RVIZ is this:
![Screenshot from 2021-08-24 14-45-46](https://user-images.githubusercontent.com/60878347/130627926-c55920ed-bafd-469e-b0e1-6d1ff1472bfb.png)



The console where I open RVIZ keeps saying this:
```
Failed to find match for field 'rgb'.
Failed to find match for field 'normal_x'.
Failed to find match for field 'normal_y'.
Failed to find match for field 'normal_z'.
Failed to find match for field 'curvature'.
```

I am not very familiar with obj or ply files and the tools you mentioned (Blender/Meshlab) but I tried to open a couple of files from [this website](https://free3d.com/) but each of them suffered from the same issue described here.
Do you think the files are faulty and I need to add the mesh normals and curvature manually as you suggested?

**Comment by marip8** [comment]
Since you're seeing the mesh show up in Rviz, I think the missing vertex normals and curvature information is not causing a problem.

I downloaded the stage mesh `.obj` file, opened it in Meshlab, and got an error saying that it could not find the "material" used to provide color for the mesh vertices. Each vertex in an `.obj` file can specify a UV coordinate in a material texture map as its color (see [here](https://en.wikipedia.org/wiki/Wavefront_.obj_file#Vertex_texture_coordinate_indices) and [here](https://www.cs.cmu.edu/~mbz/personal/graphics/obj.html) for reference). This texture map is provided in a separate `.mtl` file that is referenced by the `.obj` file. It turns out that this mesh download does not provide the `.mtl` file, so the mesh does not have color; hence the Rviz display not being colorized.

Other file formats like `.ply` and `.stl` embed color directly into the file, so you might have better luck using one of those formats. If the mesh is saved in ASCII format (opposed to binary), you can also open the file with a text editor and see what sort of information is inside (color, normals, etc.).

Even if you had an `.obj` file accompanied by a `.mtl` file, I'm not entirely sure that PCL would be able to parse out the color. If you find an `.obj` file with a `.mtl` file and test it out, let me know what you find out.

I was able to open the `.3ds` version of the mesh in Meshlab and the colors came through. I exported it as a `.ply` that you can try with this repo; [here](https://github.com/marip8/colorized_mesh_display/files/7040220/Concert.Stage.zip) is the new file.

**Comment by mac137** [comment]
Many thanks for your explanations - very clear!

I managed to open the file you provided a link to, and indeed the curvature- and normal-related warnings in the console where I open RVIZ disappeared. However, I still cannot see the colors on the mesh in RVIZ and the console keeps saying `Failed to find match for field 'rgb'.`

Here's the displayed stage without colors in RVIZ:
![Screenshot from 2021-08-24 22-19-40](https://user-images.githubusercontent.com/60878347/130691906-bc177b53-8ea7-4dfd-ab13-03a855e49058.png)

If I understood you correctly, the ply file you provided the link to should be colored now, shouldn't it?

**Comment by marip8** [comment]
My mistake; I accidentally saved the colors as face colors rather than vertex colors. Try [this file](https://github.com/marip8/colorized_mesh_display/files/7042361/concert_stage_vertex_color.zip) instead

**Comment by mac137** [comment]
Great, thank you! Now I can see colors:
![Screenshot from 2021-08-25 00-08-27](https://user-images.githubusercontent.com/60878347/130701507-6d9cf1e2-8d16-4bce-a6b4-c9990afcdc1e.png)
